# Generated by Django 5.0.8 on 2024-08-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('phone_number1', models.CharField(max_length=15, unique=True)),
                ('phone_number2', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('address', models.CharField(default='فاطمة الزهراء, قرية، ونا القس، محافظة بني سويف', max_length=600)),
                ('logo', models.ImageField(upload_to='photos/')),
                ('gmail', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('Tiktok', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('Facebook', models.CharField(blank=True, max_length=250, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='photos/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=700)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='container_of_five_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('activate', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('photo1', models.ImageField(upload_to='photos/')),
                ('photo2', models.ImageField(upload_to='photos/')),
                ('photo3', models.ImageField(upload_to='photos/')),
                ('photo4', models.ImageField(upload_to='photos/')),
                ('photo5', models.ImageField(upload_to='photos/')),
                ('weight', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('activate', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('weight', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
