# Generated by Django 5.0.8 on 2024-08-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_company',
            name='video',
            field=models.FileField(default='video1.mp4', upload_to='video/'),
            preserve_default=False,
        ),
    ]
